work/urls.py
from django.urls import path,re_path,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required, permission_required
from . import views


urlpatterns = [
    path('', login_required(views.IndexView.as_view()),name='index'),
    path('<int:year>/<int:month>/<int:day>',login_required(views.TaskCreateView.as_view()),name='day-page'),
    path('fetch_child_select', views.fetch_child_select, name="fetch_child_select"),
    path('task/delete',views.delete_task, name="delete_task"),
    path('fetch_registered_task',views.fetch_registered_task, name="fetch_registered_task"),
]

worktime/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('work.urls')),
    path('register/', include('register.urls')),
]

work/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
# Create your models here.

class AbstractLevel(models.Model):
  class Meta:
        abstract = True
  
  title = models.CharField(unique = True,max_length=255)
  description = models.CharField(null=True,blank=True,max_length=255)
  
  def __str__(self):
        return self.title

class Level1(AbstractLevel):
  pass
class Level2(AbstractLevel):
  level1 = models.ForeignKey(Level1,null=True,on_delete=models.CASCADE)
class Level3(AbstractLevel):
  level2 = models.ForeignKey(Level2,null=True,on_delete=models.CASCADE)


class Task(models.Model):
  CHOICE = ((None,'選択'),(30,'00:30'),(60,'01:00'),(90,'01:30'),(120,'02:00'),(150,'02:30'),(180,'03:00'),
            (210,'03:30'),(240,'04:00'),(270,'04:30'),(300,'05:00'),(330,'05:30'),(360,'06:00'),
            (390,'06:30'),(420,'07:00'),(450,'07:30'),(480,'08:00'),
          )
  time = models.PositiveIntegerField(choices=CHOICE)
  day = models.DateField(default=now().date())
  create_at = models.DateTimeField(auto_now_add = True,null=True)
  update_at = models.DateTimeField(auto_now = True,null=True)
  level1 = models.ForeignKey(Level1,on_delete=models.CASCADE)
  level2 = models.ForeignKey(Level2,on_delete=models.CASCADE)
  level3 = models.ForeignKey(Level3,on_delete=models.CASCADE)
  user = models.ForeignKey(User,null=True,on_delete=models.CASCADE)

work/forms.py
from .models import Task,Level1,Level2,Level3
from django import forms
from django.contrib.auth.forms import UserCreationForm

 
class TaskForm(forms.ModelForm):
  class Meta:
    model = Task
    fields = ['level1','level2','level3','day','time','user']
    widgets = {'day': forms.HiddenInput(),'user': forms.HiddenInput()}

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['day'].widget.attrs.update({'class':'form-control form-control-lg'})
    self.fields['time'].widget.attrs.update({'class':'form-control form-control-lg'})
    self.fields['level1'].widget.attrs.update({'class':'form-control form-control-lg'})
    self.fields['level2'].widget.attrs.update({'class':'form-control form-control-lg'})
    self.fields['level3'].widget.attrs.update({'class':'form-control form-control-lg'})

work/views.py
from django.shortcuts import render
from .models import *
from .forms import TaskForm
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect,JsonResponse
import datetime

class IndexView(TemplateView):
  template_name = 'work/index.html'

  def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class TaskCreateView(CreateView):
  template_name = 'work/detail.html'
  model = Task
  form_class = TaskForm
  success_url = reverse_lazy('index')

  def get_success_url(self):
    year,month,day = self.kwargs['year'],self.kwargs['month'],self.kwargs['day']
    self.success_url += f'{year}/{month}/{day}'
    return self.success_url

  def get_initial(self):
    super(TaskCreateView, self).get_initial()
    target = datetime.date(self.kwargs['year'],self.kwargs['month'],self.kwargs['day'])
    self.initial = {'day':target,'user':self.request.user.id}
    return self.initial

  def get_context_data(self,**kwargs):
    context = super(TaskCreateView, self).get_context_data(**kwargs)
    target = datetime.date(self.kwargs['year'],self.kwargs['month'],self.kwargs['day'])
    tasks = Task.objects.filter(day=target,user=self.request.user.id)
    data = {'tasks':tasks,'year':self.kwargs['year'],'month':self.kwargs['month'],'day':self.kwargs['day']}
    context.update(data)
    return context

  def post(self, request, *args, **kwargs):
    cp_request_post = request.POST.copy()
    cp_request_post['user'] = request.user.id
    self.request.POST = cp_request_post
    request.POST = cp_request_post
    return super(TaskCreateView, self).post(request, *args, **kwargs)

def fetch_child_select(request):
  try:
    num = int(request.GET.get('num'))
    level = request.GET.get('level')

    if level == 'level1':
      ids = [l2[0] for l2 in Level2.objects.filter(level1_id=num).values_list('id')]
    elif level == 'level2':
      ids = [l3[0] for l3 in Level3.objects.filter(level2_id=num).values_list('id')]
  except Exception:
    ids = []
  finally:
    result = {'ids':ids}
    return JsonResponse(result)

def delete_task(request):
  if request.POST:
    task_id = int(request.POST.get('id'))
    Task.objects.filter(id=task_id).delete()
    return JsonResponse({'msg':"削除しました"})
  else:
    return JsonResponse({'msg':"不正なメソッドです"},status=405)

def fetch_registered_task(request):
  base = request.GET.get('start_date')

  in_date_format = '%Y-%m-%dT%H:%M:%S'
  out_date_format = '%Y-%m-%d'

  base_date = datetime.datetime.strptime(base,in_date_format).date()
  start_date = base_date - datetime.timedelta(days=365)
  end_date = base_date + datetime.timedelta(days=365)
  
  tasks = Task.objects.filter(day__gte=start_date,day__lte=end_date,user_id=request.user.id).order_by('day')
  
  result = []
  display_line = 3
  flg = display_line
  for i,task in enumerate(tasks):
    if i >= 1 and tasks[i].day != tasks[i-1].day:
      flg = display_line
    if flg > 0:
      data = {
        'id':task.id,
        'title':task.level1.title,
        'start':datetime.datetime.strftime(task.day,out_date_format)
        }
      result.append(data)
      flg -= 1

  return JsonResponse({'data':result})

templates/work/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta charset="utf-8">
<title></title>
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">

{% block head %}{% endblock %}
</head>
<body>
    <div class="container-fluid">
     {% block content %}{% endblock %}
    </div>
    <script>window.load = function() { $('body').bootstrapMaterialDesign(); };</script>
</body>
</html>

templates/work/detail.html
{% extends 'base.html' %}
{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
{% endblock %}

{% load convert_time %}
{% block content %}
<br><br>
<h2>{{year}}/{{month}}/{{day}}</h2>
<div class="row">
  <div class="col-sm-9"></div>
  <div class="col-sm-3">
    <a class="float-right btn btn-lg btn-default btn-block" href="{% url 'index' %}">BACK</a>
  </div>
</div>
<form method="post">
{% csrf_token %}
  {{form.day}}
  {{form.user}}
  <div class="row">
    <div class="col-sm-10">
      <div class="row">
        <div class="col-sm-3">
          {{form.level1.label}}
        </div>
        <div class="col-sm-3">
          {{form.level2.label}}
        </div>
        <div class="col-sm-3">
          {{form.level3.label}}
        </div>
        <div class="col-sm-3">
        {{form.time.label}}
      </div>
        <div class="col-sm-3">
          {{form.level1}}
        </div>
        <div class="col-sm-3">
          {{form.level2}}
        </div>
        <div class="col-sm-3">
          {{form.level3}}
        </div>
        <div class="col-sm-3">
        {{form.time}}
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      <button style="position: absolute;bottom:0;" type="submit" class="btn btn-block btn-lg btn-raised btn-default">Send</button>
    </div>
  </div>
</form>
<div class="alert alert-info row" style="margin-top:30px;">
  <div style="display:inline" >
    <span class="col-sm-6">合計</span><span id="sum" class="col-sm-6"></span>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr><th>Level1</th><th>Level2</th><th>Level3</th><th>Time</th><th>action</th></tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr id="task_{{task.id}}">
      <td>{{task.level1}}</td><td>{{task.level2}}</td><td>{{task.level3}}</td>
      <td data-time="{{task.time}}">{{task.time|convert_time}}</td>
      <td><button class="btn btn-danger del-btn" value="{{task.id}}">delete</button></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script>
  toastr.options.timeOut = 2000
  var sum = 0
  for(let el of $('[data-time]')){
    sum += Number($(el).attr('data-time'))
  }
  var hour = ('00' + Math.floor(sum / 60)).slice(-2)
  var min = ('00' + sum % 60).slice(-2)
  $('#sum').text(`${hour}:${min}`)

  $('#id_level2').prop('disabled',true)
  $('#id_level3').prop('disabled',true)

  $('#id_level1').on('change',function(){
    $('#id_level2').prop('disabled',true).val(null)
    $('#id_level3').prop('disabled',true).val(null)
    var num = $('#id_level1 option:selected').val()
    var defered = fetchChildSelection(num,'level1')
    defered.done(function(){
      $('#id_level2').prop('disabled',false)
    })
  })

  $('#id_level2').on('change',function(){
    $('#id_level3').prop('disabled',true).prop('selected',false)
    var num = $('#id_level2 option:selected').val()
    var defered = fetchChildSelection(num,'level2')
    defered.done(function(){
      $('#id_level3').prop('disabled',false).val(null)
    })
  })

  function fetchChildSelection(num,level){
    var deferred = new $.Deferred();
    var dict = {'level1':2,'level2':3}
    $.ajax({
      url:"{% url 'fetch_child_select' %}",
      type:'GET',
      data:{
          'num':num,
          'level':level
      }
    }).done(function(res){
      var ids = res["ids"]
      var el = `#id_level${dict[level]} option:not([selected])`
      for (let op of $(el)){
        v = $(op).val()
        if(ids.indexOf(Number(v)) >= 0){
          $(op).removeClass('no-display')
        } else {
          $(op).addClass('no-display')
        }
      }
    }).always(function(res){
      el = `#id_level${dict[level]} option[selected]`
      deferred.resolve();
    })
  
  return deferred
  }

  $('.del-btn').on('click',function(){
    var value = $(this).val()
    $.ajax({
      url:"{% url 'delete_task' %}",
      type:'POST',
      data:{
          id: value,
          csrfmiddlewaretoken: '{{ csrf_token }}'
      }
    }).done(function(res){
      toastr.info(res['msg'])
      taskId = '#task_' + value
      $(taskId).remove()
    }).fail(function(res){
      if (res['msg'] == null){
        res['msg'] = "エラーが発生しました"
      }
      toastr.info(res['msg'])
    })
  })

</script>
{% endblock %}

templates/work/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/locale/ja.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/material-design-fullcalendar.css' %}">
{% endblock %}

{% block content %}
<br><br>
<div id='calendar'></div>
<script>
  $(function() {
    $('#calendar').fullCalendar({
      //themeSystem:'bootstrap4',
      header: {
          left: 'prev,next today',
          center: 'title',
          right: 'month,agendaWeek'
        },
      bootstrapFontAwesome: {
        close: 'fa-times',
        prev: 'fa-chevron-left',
        next: 'fa-chevron-right',
        prevYear: 'fa-angle-double-left',
        nextYear: 'fa-angle-double-right'
        },
      selectable: true,
      locale: 'ja',
      })
  })
  
  $('#calendar').fullCalendar({
    dayClick: function(date, jsEvent, view) {
      url = "{% url 'day-page' 99999 88888 77777 %}"
      url = url.replace(/99999/,date.year())
      url = url.replace(/88888/,date.month()+1)
      url = url.replace(/77777/,date.date())
      window.location.href = url
    }
  });
  $('.fc-day').hover(
    function(){
    $(this).css({'background-color':'#ffe4e1'})
    },
    function(){
    $(this).css({'background-color':''})
    },
  )

  function registerEvent(){
    $.ajax({
      url:"{% url 'fetch_registered_task' %}",
      type:'GET',
      data:{
          'start_date':$('#calendar').fullCalendar('getDate').format()
      }
    }).done(function(res){
      var tasks = res['data']
      for (let task of tasks){
        event = {id: Number(task['id']),title: task['title'], start:task['start']}
        $('#calendar').fullCalendar('renderEvent', event, true)
      }
    })
  }
  window.load = registerEvent()
  
  $('#calendar').fullCalendar({
    viewRender: function(view){
      registerEvent()
    }
  })

  function onResize() {
    if (window.innerWidth <= 768) {
      $('#calendar').fullCalendar('changeView', 'listMonth')
    } else {
      $('#calendar').fullCalendar('changeView', 'month')
    }
  }
  $(function(){
    $(window).resize(function(){
      onResize();
    });
  })
  

</script>

{% endblock %}